
package gui;

import javax.swing.*;


public class StartFrame extends javax.swing.JPanel {

    /**
     * Creates new form StartFrame
     */
    public StartFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scheduleButtonPanel = new javax.swing.JPanel();
        scheduleButton = new javax.swing.JButton();
        ActivityButtonPanel = new javax.swing.JPanel();
        listActivityButton = new javax.swing.JButton();
        grpActivityButton = new javax.swing.JButton();
        visActivityButton = new javax.swing.JButton();
        privActivityButton = new javax.swing.JButton();
        occupantButtonPanel = new javax.swing.JPanel();
        occupantButton = new javax.swing.JButton();
        staffButtonPanel1 = new javax.swing.JPanel();
        staffButton1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(1200, 700));

        scheduleButtonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Schema", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N
        scheduleButtonPanel.setPreferredSize(new java.awt.Dimension(395, 127));

        scheduleButton.setText("Schema Hanterare");

        javax.swing.GroupLayout scheduleButtonPanelLayout = new javax.swing.GroupLayout(scheduleButtonPanel);
        scheduleButtonPanel.setLayout(scheduleButtonPanelLayout);
        scheduleButtonPanelLayout.setHorizontalGroup(
            scheduleButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scheduleButtonPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(scheduleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        scheduleButtonPanelLayout.setVerticalGroup(
            scheduleButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scheduleButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scheduleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        ActivityButtonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aktivitet", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N

        listActivityButton.setText("Lista Aktiviteter");

        grpActivityButton.setText("Gruppaktivitet");

        visActivityButton.setText("Besöksaktivitet");

        privActivityButton.setText("Privat Aktivitet");

        javax.swing.GroupLayout ActivityButtonPanelLayout = new javax.swing.GroupLayout(ActivityButtonPanel);
        ActivityButtonPanel.setLayout(ActivityButtonPanelLayout);
        ActivityButtonPanelLayout.setHorizontalGroup(
            ActivityButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ActivityButtonPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(grpActivityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(visActivityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(privActivityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(listActivityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        ActivityButtonPanelLayout.setVerticalGroup(
            ActivityButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ActivityButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ActivityButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listActivityButton, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(grpActivityButton, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(visActivityButton, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(privActivityButton, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addContainerGap())
        );

        occupantButtonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Boende", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N
        occupantButtonPanel.setPreferredSize(new java.awt.Dimension(395, 127));

        occupantButton.setText("Profilhantering");

        javax.swing.GroupLayout occupantButtonPanelLayout = new javax.swing.GroupLayout(occupantButtonPanel);
        occupantButtonPanel.setLayout(occupantButtonPanelLayout);
        occupantButtonPanelLayout.setHorizontalGroup(
            occupantButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, occupantButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(occupantButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
        );
        occupantButtonPanelLayout.setVerticalGroup(
            occupantButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(occupantButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(occupantButton, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        staffButtonPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N
        staffButtonPanel1.setPreferredSize(new java.awt.Dimension(395, 127));

        staffButton1.setText("Profilhantering");
        staffButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout staffButtonPanel1Layout = new javax.swing.GroupLayout(staffButtonPanel1);
        staffButtonPanel1.setLayout(staffButtonPanel1Layout);
        staffButtonPanel1Layout.setHorizontalGroup(
            staffButtonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffButtonPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(staffButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        staffButtonPanel1Layout.setVerticalGroup(
            staffButtonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffButtonPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(staffButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ActivityButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scheduleButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(occupantButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(staffButtonPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(ActivityButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scheduleButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(occupantButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffButtonPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(271, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void staffButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ActivityButtonPanel;
    private javax.swing.JButton grpActivityButton;
    private javax.swing.JButton listActivityButton;
    private javax.swing.JButton occupantButton;
    private javax.swing.JPanel occupantButtonPanel;
    private javax.swing.JButton privActivityButton;
    private javax.swing.JButton scheduleButton;
    private javax.swing.JPanel scheduleButtonPanel;
    private javax.swing.JButton staffButton1;
    private javax.swing.JPanel staffButtonPanel1;
    private javax.swing.JButton visActivityButton;
    // End of variables declaration//GEN-END:variables

    public JButton getGrpButton() { return grpActivityButton; }
    public JButton getPrivButton() { return privActivityButton; }
    public JButton getVisButton() { return visActivityButton; }
    public JButton getListButton() { return listActivityButton; }
    
    
}
